### ISSUE TITLE
Favicons are still boilerplate

### ISSUE THREAD

**Issue by PhilippJust** [wilhelmstinkts/webapp#16]
The favicons of the page are still the boilerplate icons from [h5bp](https://github.com/h5bp).
@pixelbaker Could you please bake us some pixels to a nice icon?

**Comment by pixelbaker** [comment]
Sure thing. I am currently on vacation with limited access to Internet. I try to bake it asap

**Comment by PhilippJust** [comment]
No need to hurry. Enjoy your vacation!

**Comment by pixelbaker** [comment]
Here you go. The file contains various resolutions. I guess the favicon.ico will do the trick but in case you know a bit more about favicons you might know, hot to make use of the other resolutions. [favicons.zip](https://github.com/wilhelmstinkts/webapp/files/4699681/favicons.zip)

**Comment by pixelbaker** [comment]
<img width="356" alt="Screenshot 2020-05-29 at 06 31 52" src="https://user-images.githubusercontent.com/29891579/83221457-2bb95300-a176-11ea-9c3d-a21d59c19e4b.png">
Our webpage now also uses the favicon.ico file.
