### ISSUE TITLE
Api for location queries

### ISSUE THREAD

**Issue by PhilippJust** [wilhelmstinkts/webapp#2]
For later features, this might become interesting:
http://nominatim.org/

**Comment by pixelbaker** [comment]
That looks indeed good. Thx

**Comment by PhilippJust** [comment]
And I need to implement it in the frontend.
Whenever I try accessing it from the backend, I get 403 errors that are likely to be caused by a violation of [nominatim's usage policy](https://operations.osmfoundation.org/policies/nominatim/).
