### ISSUE TITLE
The intensity slider needs some tweaking

### ISSUE THREAD

**Issue by pixelbaker** [wilhelmstinkts/webapp#23]
I like to make clear that the slide dragged to the left means less intense and to the right very intense.

I also would like the label to be above the slide or to the left.

The label "Intensität" on the top of the slider would free space to the left and to the right of the slider for additional labels like "schwach" and "stark".

What do you think?

**Comment by PhilippJust** [comment]
So something like

(1)
```
Intensität
Schwach |----Slider------| Stark
```

Or 

(2)
```
Intensität
    |----Slider------| 
Schwach            Stark
```

I think I'd prefer (2) optically. Are you d'accord?

**Comment by pixelbaker** [comment]
Yeah, go for it
