### ISSUE TITLE
Auto-fill Form

### ISSUE THREAD

**Issue by PhilippJust** [wilhelmstinkts/webapp#8]
The form should be autofilled with given name, surname and email address whenever possible. We should consider using these attributes https://stackoverflow.com/questions/7223168/how-to-trigger-autofill-in-google-chrome/9795126#9795126

**Comment by pixelbaker** [comment]
![image](https://user-images.githubusercontent.com/29891579/82140187-24b54b00-982e-11ea-9cac-354035c10561.png)
![image](https://user-images.githubusercontent.com/29891579/82140189-2d0d8600-982e-11ea-9141-59d5b8576b87.png)
![image](https://user-images.githubusercontent.com/29891579/82140191-3139a380-982e-11ea-8498-47ff6c3477e2.png)

**Comment by pixelbaker** [comment]
Somehow the street doesn’t get filled. But could also be a problem on my end

**Comment by PhilippJust** [comment]
Cool. It behaves exactly as intended. :)
The problem that the address is not filled shows a usability issue: You're not supposed to put your address of residence in but the address where you experience the stink.

So maybe there should be some paragraphs like:
Wer bist du?
Wo stinkt es?
Wonach stinkt es?

To make clear that you're not supposed to put your home address in there unless that's where it stinks :)

What do you think?
